web:
  build: "."
  links:
    - "postgres"
  ports:
    - "8080:8080"
postgres:
  image: "postgres:latest"
  volumes_from:
    - "postgres_data"
  environment:
    POSTGRES_PASSWORD: "temp123"
    PGDATA: "/var/lib/postgresql/data/pgdata"
  ports:
    - "5432:5432"
postgres_data:
  image: 'tianon/true'
  volumes:
    - "/var/lib/postgresql/data/pgdata"

